# Numpy

In [1]:
import numpy as np

In [5]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
# get Dimentions
print(a.ndim)
print(b.ndim)

1
2


In [10]:
# get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [11]:
# get type
a.dtype

dtype('int32')

In [13]:
c = np.array([1,2,3], dtype='int16')
c.dtype

dtype('int16')

In [17]:
# get size
print(a.itemsize)
print(c.itemsize)

4
2


In [19]:
# get total size
a.nbytes

12

## Accessing/changing specific elements of row & column

In [20]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
# get a specific element [r, c]
a[1, 5]

13

In [22]:
# get a specific row
a[0, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [23]:
# get a specific col
a[:, 0]

array([1, 8])

In [24]:
# slicing
a[0, 1:6:2]

array([2, 4, 6])

In [28]:
a[1, 6] = 15
print(a)

a[:, 2] = [0, 0]
print(a)

a[0, :] = 0
print(a)

[[ 1  2  0  4  5  6  7]
 [ 8  9  0 11 12 13 15]]
[[ 1  2  0  4  5  6  7]
 [ 8  9  0 11 12 13 15]]
[[ 0  0  0  0  0  0  0]
 [ 8  9  0 11 12 13 15]]


## Initializing Different type of array

In [31]:
# all 0s matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [32]:
# all 1s matrix
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [34]:
# any other number
np.full((4,2), 99)

array([[99, 99],
       [99, 99],
       [99, 99],
       [99, 99]])

In [36]:
# any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [37]:
# random decimal numbers
np.random.rand(4,2)

array([[0.849141  , 0.307558  ],
       [0.1905839 , 0.24981895],
       [0.48311204, 0.65897507],
       [0.83668015, 0.89046463]])

In [38]:
# any other random
np.random.random_sample(a.shape)

array([[0.12437561, 0.52171937, 0.32575445, 0.78730632, 0.97017155,
        0.4845893 , 0.13833082],
       [0.57881722, 0.35767713, 0.51815391, 0.11352813, 0.65262919,
        0.74162769, 0.89117529]])

In [40]:
# random int number
np.random.randint(10, size=(3,3))

array([[7, 5, 2],
       [6, 8, 5],
       [9, 7, 6]])

In [41]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
# repeat an array
arr = np.array([[1,2,3]])
print(np.repeat(arr, 3, axis=0))

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [48]:
output = np.ones((5,5))

z = np.zeros((3,3))
z[1,1] = 9

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Maths

In [50]:
arr = np.array([0,1,2])
print(a)

[[ 0  0  0  0  0  0  0]
 [ 8  9  0 11 12 13 15]]


In [53]:
arr + 2

array([2, 3, 4])

In [54]:
arr - 2

array([-2, -1,  0])

In [55]:
arr * 2

array([0, 2, 4])

In [58]:
arr / 2

array([0. , 0.5, 1. ])

In [59]:
arr ** 2

array([0, 1, 4], dtype=int32)

In [60]:
# take trigo
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684])

### Linear Algebra

In [61]:
a = np.ones((3,2))
print('a = ', a)

b = np.full((2,3), 2)
print('b = ', b)

np.matmul(a,b)

a =  [[1. 1.]
 [1. 1.]
 [1. 1.]]
b =  [[2 2 2]
 [2 2 2]]


array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [63]:
# determinent of a matrix
c = np.identity(3)
np.linalg.det(c)

1.0

### Reorganizing array

In [64]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [67]:
# Vertical Stack
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [68]:
# horizontal stack
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.hstack([v1,v2,v2,v1])

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8, 1, 2, 3, 4])